### ISSUE TITLE
BMP RLE error or support?

### ISSUE THREAD

**Issue by fionawhim** [adafruit/Adafruit_CircuitPython_ImageLoad#20]
Hi! I ran into a problem where ImageMagick’s `convert` was generating RLE-compressed BMP images, which were then displaying as garbage when I loaded them.

Would you accept a PR that either:
 
 - Added support for loading an RLE-compressed image
 - Raised an Error if it detected an RLE-compressed image (similar to how it errors on "true color" BMPs now)

I’m happy to provide either.

**Comment by matt-land** [comment]
Hi Fiona,

Thanks for your interest. We would prefer the former but would accept either. 
In addition, if would help us if you can provide two sample images in the RLE-compressed format. 

The first image would normally be a "large" image (320x240 max) that can be used by one of the maintainers to manually test your code on hardware. If decompression of this new image type is CPU intense (aka it takes longer than a minute to load), make it smaller. 

The second image file should be smaller, about 16x16. It will be used for building an automated regression test ( make sure future commits never accidentally break your code). You do not have to write the automated test. 

Please provide download links for the two images in the PR message.

On our end, the process normally takes a few days from "I've opened a PR and my build is passing" for someone to review it,  test it on hardware, and merge. After that, a release will be created with the new functionality.

Any other questions, feel free to ask.
