### ISSUE TITLE
negative height check doesn't work without longint

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_ImageLoad#28]
@FoamyGuy pointed out in discord that https://github.com/adafruit/Adafruit_CircuitPython_ImageLoad/blob/0c1a28ad015f5bc9b25c1c5e9812f7f8735f2471/adafruit_imageload/bmp/indexed.py#L75-L76
causes an error on import if longints aren't enabled (e.g. on pewpew_m4).

@cogliano pinging you as you added the PR that supports negative heights. Perhaps something can be done earlier in the call chain

**Comment by kevinjwalters** [comment]
Any thoughts on [CLUE OnDiskBitmap returning strange values](https://forums.adafruit.com/viewtopic.php?f=65&t=168292). He's got a negative height `bmp` there.
