### ISSUE TITLE
Provide default behavior for bitmap and palette parameters?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_ImageLoad#36]
This is currently the simplest load statement:
```python
image, palette = adafruit_imageload.load("omg_cute_kitteh.bmp", bitmap=displayio.Bitmap, palette=displayio.Palette)
```
Those options for the `bitmap` and `palette` parameter probably cover the majority of use cases. Could we make them default? That would then allow for:
```python
image, palette = adafruit_imageload.load("omg_cute_kitteh.bmp")
```
The above statement currently runs without error, but returns `NoneType`s.

**Comment by caternuson** [comment]
@tannewt Thoughts on this? This feels like one of those things where it's like this for a reason, but I'm just not seeing or understanding it. Thanks :)

**Comment by tannewt** [comment]
I don't see a reason not to support it.
