### ISSUE TITLE
adafruit_imageload missing 'bmp' directory in Adafruit_CircuitPython_Bundle releases

### ISSUE THREAD

**Issue by cstanke** [adafruit/Adafruit_CircuitPython_ImageLoad#5]
The ```adafruit_imageload``` library includes a ```bmp``` directory in its source which is not included in the ```Adafruit_CircuitPython_Bundle``` releases. As a result, importing and trying to use ```adafruit_imageload``` from ```Adafruit_CircuitPython_Bundle``` results in the error:

```ImportError: no module named 'adafruit_imageload.bmp'```

The problem can be fixed by manually dragging the ```bmp``` directory from ```adafruit_imageload``` source to the ```adafruit_imageload``` directory in the ```Adafruit_CircuitPython_Bundle``` release. It should probably be corrected in the ```Adafruit_CircuitPython_Bundle``` release build process however.

**Comment by sommersoft** [comment]
@cstanke,

Thanks for bringing this issue up! We'll start discussing a way to mitigate this. There are a couple options I can think of to address this, to include placing the `bmp` folder in the bundle or changing the library structure.

**Comment by sommersoft** [comment]
This is now fixed in the latest bundle.
