### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_ImageLoad#56]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_imageload/pnm/ppm_binary.py:23
- [ ] adafruit_imageload/pnm/ppm_ascii.py:23
- [ ] adafruit_imageload/pnm/ppm_ascii.py:54
- [ ] adafruit_imageload/pnm/pbm_binary.py:23
- [ ] adafruit_imageload/pnm/pbm_binary.py:44
- [ ] adafruit_imageload/pnm/pbm_binary.py:53
- [ ] adafruit_imageload/pnm/pbm_ascii.py:23
- [ ] adafruit_imageload/pnm/pgm/binary.py:19
- [ ] adafruit_imageload/pnm/pgm/binary.py:43
- [ ] adafruit_imageload/pnm/pgm/ascii.py:19
- [ ] adafruit_imageload/pnm/pgm/ascii.py:55
- [ ] adafruit_imageload/bmp/negative_height_check.py:12
- [ ] adafruit_imageload/gif.py:23
- [ ] adafruit_imageload/gif.py:60
- [ ] adafruit_imageload/gif.py:81
- [ ] adafruit_imageload/gif.py:98
- [ ] adafruit_imageload/gif.py:112
- [ ] adafruit_imageload/gif.py:136
- [ ] adafruit_imageload/pnm/pgm/\_\_init\_\_.py:20
- [ ] adafruit_imageload/pnm/\_\_init\_\_.py:23
- [ ] adafruit_imageload/bmp/indexed.py:26
- [ ] adafruit_imageload/bmp/indexed.py:125
- [ ] adafruit_imageload/bmp/\_\_init\_\_.py:20
- [ ] adafruit_imageload/\_\_init\_\_.py:20

**Comment by matt-land** [comment]
intending to finish this at Pycon 2022 sprints

**Comment by matt-land** [comment]
PR opened, ready for review
