### ISSUE TITLE
AttributeError: 'Bitmap' object has no attribute '_load_row'

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_ImageLoad#6]
Guessing something's changed and just needs updating here.

```python
Adafruit CircuitPython 4.0.0-beta.5 on 2019-03-17; Adafruit PyPortal with samd51j20
>>> import displayio
>>> import adafruit_imageload
>>> image, palette = adafruit_imageload.load("/4bit.bmp", bitmap=displayio.Bitmap, palette=displayio.Palette)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_imageload/__init__.py", line 51, in load
  File "adafruit_imageload/__init__.py", line 49, in load
  File "adafruit_imageload/bmp/__init__.py", line 56, in load
  File "adafruit_imageload/bmp/indexed.py", line 80, in load
AttributeError: 'Bitmap' object has no attribute '_load_row'
>>> 
```

**Comment by mad-ned** [comment]
I'm getting the same issue, using the 4.0.1 circuitpython and lib version 20190528

**Comment by caternuson** [comment]
@tannewt I think we just need to do a version bump to tag a release and get the updates in the bundle? Looks like @sommersoft fixed the issue #5 with the subdir not getting included with #31. So I think everything is good to go.

**Comment by tannewt** [comment]
@caternuson Yup! Will tag a release right now. Thanks!

**Comment by tannewt** [comment]
Fixed by #7. Will release shortly as 0.9.0.

**Comment by tannewt** [comment]
0.9.1 should fix this!

**Comment by mad-ned** [comment]
confirmed, I was able to display bitmaps with the latest 0601 release. thanks!
