### ISSUE TITLE
Add JPG to Imageload

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/Adafruit_CircuitPython_ImageLoad#79]
Not sure if imageload has JPG capability.  RTD is lacking details.  Would very much appreciate a JPG simpletest example.

**Comment by makermelissa** [comment]
I don't believe it does. I'd recommend using [jpegio](https://docs.circuitpython.org/en/latest/shared-bindings/jpegio/index.html).

**Comment by DJDevon3** [comment]
I find it odd that every other file type can be used by imageload except for JPG.  I did figure out how to use jpegio eventually which has drastically different syntax than imageload.  For consistency it would be nice to have JPG in imageload.  I have no idea if that's feesible, a bad idea, etc...

I didn't realize JPG wasn't in imageload when I created this request.  Should I change the title to "Please add JPG to Imageload"?  Is that even a valid request I have no idea.

**Comment by makermelissa** [comment]
jpeg is much more complex than the other types. I think it has been attempted before, but never successful. Maybe somebody can reverse engineer jpegio to add it?

**Comment by dhalbert** [comment]
I thought I was suggesting using `jpegio` in this library. I didn't mean it should be reimplemented.

**Comment by DJDevon3** [comment]
Yes, that's what I meant, if its possible.  Doesn't matter if it's another layer of abstraction. The consistency for usage would be welcomed.

**Comment by makermelissa** [comment]
I'm not sure if jpegio is enabled for most boards or not. If it is, we could just add a layer to this library that calls jpegio. If not, then it may be useful to add for boards that have less flash for CP.

**Comment by DJDevon3** [comment]
SWEET! 🎉
