### ISSUE TITLE
Feature Request: PNG Tilegrid Inflator

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/Adafruit_CircuitPython_ImageLoad#86]
@FoamyGuy Now that we have transparent PNG support (as of this week)
This is a request for tilegrid inflator to support PNG use instead of solely using transparent indexed BMP.  I use button and sprite_button in most of my touch GUI projects and they rely on tilegrid inflator for the button background image.

There are probably many libraries that can now add transparent PNG support. I can't speak to every use for everyone. For me, this would be the next most impactful update for PNG transparency integration.

**Comment by deshipu** [comment]
What would need to be added/changed exactly? It doesn't just work?
